aws_access_key_id: {{cookiecutter.aws_access_key_id}}
aws_secret_access_key: {{cookiecutter.aws_secret_access_key}}
aws_default_region: {{cookiecutter.aws_default_region}}
master_account_id: '{{cookiecutter.master_account_id}}'
master_admin_iam_username: '{{cookiecutter.master_admin_iam_username}}'
