AWSTemplateFormatVersion: '2010-09-09'

Description: Grants the AIM CLI access to this AWS account

Parameters:

  AIMAWSAccountId:
    Type: String
    Default: '1234567890'
    Description: AWS Account ID of your Administrator Account

  AIMIAMUser:
    Type: String
    Default: 'you@example.com'
    Description: IAM user name in your Administrator Account to delegate access to

Resources:

  DelegateIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'AIM-Adminsitrator-Cross-Account-Delegate-Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AIMAWSAccountId}:user/${AIMIAMUser}'
            Action: sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

Outputs:

  DelegateIAMRoleName:
    Value: !Ref DelegateIAMRole

  DelegateIAMRoleArn:
    Value: !GetAtt DelegateIAMRole.Arn

  SigninUrl:
    Value: !Sub 'https://signin.aws.amazon.com/switchrole?account=${AWS::AccountId}&roleName=${DelegateIAMRole}'
